'use client';
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import "../styles/globals.css";
import { Header } from "@/components/header";



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <Head>
        <title>Tarefas+ | Organize</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
       <SessionProvider>
          <Header />
           {children}
        </SessionProvider>

      </body>
    </html>
  );
}